legacy_pim_api_measure_family_list:
    path: /measure-families
    defaults: { _controller: legacy_pim_api.controller.measure_family:listAction, _format: json }
    methods: [GET]

legacy_pim_api_measure_family_get:
    path: /measure-families/{code}
    defaults: { _controller: legacy_pim_api.controller.measure_family:getAction, _format: json }
    methods: [GET]

pim_api_measurement_family_get:
    path: /measurement-family
    defaults: { _controller: pim_api.controller.measurement_family, _format: json }
    methods: [GET]
